# Use postgres/example user/password credentials
version: '3.7'

services:
  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_DATABASE: postdb
      POSTGRES_USER: postdb
      POSTGRES_PASSWORD: postdb!123